
import { Amplify } from 'aws-amplify';
import amplifyconfig from '../amplifyconfiguration.json' assert { type: 'json' };

import { generateClient } from 'aws-amplify/api';
import { createUnit } from '../graphql/mutations.js';

Amplify.configure(amplifyconfig);

const client = generateClient();

// Sample Units data
const unitsList = [
  {
    id: 1,
    ranking: 1,
    address: "101, 123 Main St",
    status: "Visited",
    statusDate: "2024-01-15",
    site: "Zillow",
    rent: "$2000",
    available: "2024-02-01",
    size: "850 sqft",
    naturalLight: 4,
    modernBuilding: 5,
    quiet: 3,
    balcony: "Yes",
    goodViews: 5,
    nearbyParks: 4,
    ac: "Yes",
    cornerUnit: "No",
    wifi: "Yes",
    furnished: "No",
  },
  {
    id: 2,
    ranking: 2,
    address: "202, 456 Elm St",
    status: "Interested",
    statusDate: "2024-02-10",
    site: "Craigslist",
    rent: "$1800",
    available: "2024-03-01",
    size: "780 sqft",
    naturalLight: 3,
    modernBuilding: 4,
    quiet: 4,
    balcony: "No",
    goodViews: 2,
    nearbyParks: 5,
    ac: "Yes",
    cornerUnit: "Yes",
    wifi: "Yes",
    furnished: "Yes",
  },
  {
    id: 3,
    ranking: 3,
    address: "303, 789 Oak St",
    status: "Rejected",
    statusDate: "2024-01-25",
    site: "Realtor",
    rent: "$2200",
    available: "2024-03-15",
    size: "920 sqft",
    naturalLight: 5,
    modernBuilding: 3,
    quiet: 2,
    balcony: "Yes",
    goodViews: 4,
    nearbyParks: 3,
    ac: "No",
    cornerUnit: "No",
    wifi: "No",
    furnished: "No",
  },
  {
    id: 4,
    ranking: 4,
    address: "404, 101 Pine St",
    status: "Visited",
    statusDate: "2024-02-05",
    site: "Zillow",
    rent: "$2100",
    available: "2024-04-01",
    size: "900 sqft",
    naturalLight: 4,
    modernBuilding: 4,
    quiet: 5,
    balcony: "Yes",
    goodViews: 3,
    nearbyParks: 4,
    ac: "Yes",
    cornerUnit: "Yes",
    wifi: "Yes",
    furnished: "No",
  },
  {
    id: 5,
    ranking: 5,
    address: "505, 202 Cedar St",
    status: "Interested",
    statusDate: "2024-01-30",
    site: "Zillow",
    rent: "$2300",
    available: "2024-03-10",
    size: "950 sqft",
    naturalLight: 5,
    modernBuilding: 5,
    quiet: 5,
    balcony: "No",
    goodViews: 5,
    nearbyParks: 5,
    ac: "Yes",
    cornerUnit: "Yes",
    wifi: "No",
    furnished: "Yes",
  },
  {
    id: 6,
    ranking: 6,
    address: "606, 303 Birch St",
    status: "Rejected",
    statusDate: "2024-02-12",
    site: "Craigslist",
    rent: "$2500",
    available: "2024-02-28",
    size: "1100 sqft",
    naturalLight: 4,
    modernBuilding: 4,
    quiet: 3,
    balcony: "Yes",
    goodViews: 4,
    nearbyParks: 3,
    ac: "Yes",
    cornerUnit: "No",
    wifi: "Yes",
    furnished: "No",
  },
  {
    id: 7,
    ranking: 7,
    address: "707, 404 Maple St",
    status: "Visited",
    statusDate: "2024-01-20",
    site: "Realtor",
    rent: "$1900",
    available: "2024-03-05",
    size: "870 sqft",
    naturalLight: 3,
    modernBuilding: 3,
    quiet: 4,
    balcony: "No",
    goodViews: 3,
    nearbyParks: 4,
    ac: "Yes",
    cornerUnit: "Yes",
    wifi: "No",
    furnished: "Yes",
  },
  {
    id: 8,
    ranking: 8,
    address: "808, 505 Willow St",
    status: "Interested",
    statusDate: "2024-01-18",
    site: "Zillow",
    rent: "$2000",
    available: "2024-04-10",
    size: "800 sqft",
    naturalLight: 4,
    modernBuilding: 4,
    quiet: 5,
    balcony: "Yes",
    goodViews: 5,
    nearbyParks: 4,
    ac: "Yes",
    cornerUnit: "No",
    wifi: "Yes",
    furnished: "No",
  },
  {
    id: 9,
    ranking: 9,
    address: "909, 606 Poplar St",
    status: "Rejected",
    statusDate: "2024-02-02",
    site: "Craigslist",
    rent: "$1700",
    available: "2024-03-20",
    size: "780 sqft",
    naturalLight: 3,
    modernBuilding: 2,
    quiet: 3,
    balcony: "No",
    goodViews: 2,
    nearbyParks: 3,
    ac: "No",
    cornerUnit: "Yes",
    wifi: "Yes",
    furnished: "Yes",
  },
  {
    id: 10,
    ranking: 10,
    address: "1010, 707 Redwood St",
    status: "Visited",
    statusDate: "2024-02-08",
    site: "Realtor",
    rent: "$2400",
    available: "2024-05-01",
    size: "980 sqft",
    naturalLight: 5,
    modernBuilding: 5,
    quiet: 5,
    balcony: "Yes",
    goodViews: 5,
    nearbyParks: 4,
    ac: "Yes",
    cornerUnit: "No",
    wifi: "Yes",
    furnished: "No",
  },
];


const seedUnits = async () => {
  try {
    for (const unit of unitsList) {
      const response = await client.graphql({
        query: createUnit,
        variables: { input: unit }
      });
      console.log('Created unit:', response.data.createUnit);
    }
    console.log('Seeding complete!');
  } catch (error) {
    console.error('Error seeding units:', error);
  }
};

// Run the script
seedUnits();
